"""empty message

Revision ID: 5b982f97058b
Revises: e64937d9154d
Create Date: 2023-08-06 16:59:56.121351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b982f97058b'
down_revision = 'e64937d9154d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserDetail', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_UserDetail_nickname'), ['nickname'])

    with op.batch_alter_table('UserLogin', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_UserLogin_userid'), ['userid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserLogin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_UserLogin_userid'), type_='unique')

    with op.batch_alter_table('UserDetail', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_UserDetail_nickname'), type_='unique')

    # ### end Alembic commands ###
